Repository DevSpen/scam-links, pull requests merged in 2022-02, with the labels that each got.

#74 Update links.txt
  src/links.txt
Labels: enhancement, size/XL

#75 Update links.txt
  src/links.txt
Labels: enhancement, size/XXL

#76 Added a new phishing link
  src/links.txt
Labels: enhancement, size/XS

#77 new link in links.txt
  src/links.txt
Labels: enhancement, size/XS

#78 Update links.txt
  src/links.txt
Labels: enhancement, size/XL

#80 Update links.txt
  src/links.txt
Labels: enhancement, size/XL

#83 Add links from #82
  src/links.txt
Labels: enhancement, size/XS

#84 Update links.txt
  src/links.txt
Labels: enhancement, size/XXL

#85 Add new link and slash
  src/links.txt
Labels: enhancement, size/XS

#86 add links, remove dupe and alphabetise one entry
  src/links.txt
Labels: enhancement, size/S

#88 Update links.txt
  src/links.txt
Labels: enhancement, size/XS

#89 Update links.txt
  src/links.txt
Labels: enhancement, size/XXL

#93 Update links.txt
  src/links.txt
Labels: enhancement, size/S

#94 Added new phishing links
  src/links.txt
Labels: enhancement, size/S

#95 Update links.txt
  src/links.txt
Labels: enhancement, size/S

#96 Added new phishing links
  src/links.txt
Labels: enhancement, size/XS

#97 Update links.txt
  src/links.txt
Labels: enhancement, size/XXL

#98 Remove blankspace
  src/links.txt
Labels: bug, size/XS, patch

#99 Added new phishing links
  src/links.txt
Labels: enhancement, size/XS

#100 Update links.txt
  src/links.txt
Labels: size/XS
