Repository DevSpen/scam-links, pull requests merged in 2022-05, with the labels that each got.

#133 Update links.txt
  src/links.txt
Labels: enhancement, size/XL

#134 add links
  src/links.txt
Labels: enhancement, size/L

#135 Update links.txt
  src/links.txt
Labels: enhancement, size/XS

#136 New links
  src/links.txt
Labels: enhancement, size/S

#137 More urls
  src/links.txt
Labels: enhancement, size/L

#138 New Links
  src/links.txt
Labels: enhancement, size/S

#139 add links
  src/links.txt
Labels: enhancement, size/M

#140 removed non-scam url
  src/links.txt
Labels: bug, enhancement, size/XS
