Repository DevSpen/scam-links, pull requests merged in 2022-01, with the labels that each got.

#11 a
  src/links.txt
  src/malicious-terms.txt
  src/trailing-slashes.txt
Labels: enhancement

#15 Update Links / Terms
  src/links.txt
  src/malicious-terms.txt
Labels: enhancement

#16 Update links.txt
  src/links.txt
Labels: enhancement

#19 Update links.txt
  src/links.txt
Labels: enhancement

#20 Update links.txt
  src/links.txt
Labels: enhancement

#21 Update malicious-terms.txt
  src/malicious-terms.txt
Labels: enhancement

#23 Update links and slashes
  src/links.txt
  src/trailing-slashes.txt
Labels: enhancement

#22 Update links.txt
  src/links.txt
Labels: enhancement

#24 Update link.txt
  src/links.txt
Labels: enhancement

#25 Update links.txt
  src/links.txt
Labels: enhancement

#26 Update links.txt
  src/links.txt
Labels: enhancement, size/L

#27 Update links.txt
  src/links.txt
Labels: enhancement, size/XS

#28 Update links.txt
  src/links.txt
Labels: enhancement, size/L

#29 Update links.txt
  src/links.txt
Labels: enhancement, size/L

#31 Update links.txt
  src/links.txt
Labels: enhancement, size/L

#34 Update links.txt
  src/links.txt
Labels: enhancement, size/XL

#35 Update links.txt
  src/links.txt
Labels: enhancement, size/M

#37 Add some domains and deletion of duplicates
  src/links.txt
Labels: enhancement, size/L

#39 Update links.txt
  src/links.txt
Labels: size/M

#40 add link
  src/links.txt
Labels: enhancement, size/XS

#41 Update links.txt
  src/links.txt
Labels: enhancement, size/L

#43 Removed words from list
  src/links.txt
Labels: size/S

#44 add link
  src/links.txt
Labels: enhancement, size/S

#45 Update Links.txt
  src/links.txt
Labels: enhancement, size/L

#46 Update links.txt
  src/links.txt
Labels: size/XL

#47 add link
  src/links.txt
Labels: enhancement

#48 remove dupes
  src/links.txt
Labels: size/S

#50 Update links.txt
  src/links.txt
Labels: enhancement, size/L

#51 add link
  src/links.txt
Labels: size/XS

#53 Update Links.txt
  src/links.txt
Labels: enhancement, size/L

#56 Add links
  src/links.txt
Labels: enhancement, size/XS

#57 Update links.txt
  src/links.txt
Labels: enhancement, size/L

#58 add link
  src/links.txt
Labels: enhancement, size/XS

#61 Update links.txt
  src/links.txt
Labels: enhancement, size/XL

#62 Update links.txt
  src/links.txt
Labels: enhancement, size/L

#63 Cherry Pick from #60
  src/malicious-terms.txt
Labels: enhancement, size/XS

#64 Update links.txt
  src/links.txt
Labels: enhancement, size/L

#65 Update links.txt
  src/links.txt
Labels: enhancement, size/L

#66 Update links.txt
  src/links.txt
Labels: enhancement, size/L

#67 Update links.txt
  src/links.txt
Labels: enhancement, size/L

#68 Update links.txt
  src/links.txt
Labels: enhancement

#69 Update links.txt
  src/links.txt
Labels: enhancement, size/XL

#71 Update links.txt
  src/links.txt
Labels: enhancement, size/XL

#73 New phishing link
  src/links.txt
Labels: enhancement, size/S

#72 Update link.txt
  src/links.txt
Labels: enhancement, size/XL
